version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_PERPLEXITY_API_KEY=${REACT_APP_PERPLEXITY_API_KEY}
    restart: unless-stopped 