services:
  - type: web
    name: amazon-seller-dashboard
    env: node
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: REACT_APP_GEMINI_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 